//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace DBlog.Web.UnitTests.WebServices.Blog {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BlogSoap", Namespace="http://dblock.org/ns/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransitObject))]
    public partial class Blog : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLoginByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOrUpdateLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLoginsCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLoginsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTopicByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOrUpdateTopicOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTopicsCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTopicsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteTopicOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBlogByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBlogsCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBlogsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTitleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCopyrightOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDescriptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUptimeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Blog() {
            this.Url = global::DBlog.Web.UnitTests.Properties.Settings.Default.DBlog_Web_UnitTests_WebServices_Blog_Blog;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event GetLoginCompletedEventHandler GetLoginCompleted;
        
        /// <remarks/>
        public event GetLoginByIdCompletedEventHandler GetLoginByIdCompleted;
        
        /// <remarks/>
        public event CreateOrUpdateLoginCompletedEventHandler CreateOrUpdateLoginCompleted;
        
        /// <remarks/>
        public event GetLoginsCountCompletedEventHandler GetLoginsCountCompleted;
        
        /// <remarks/>
        public event GetLoginsCompletedEventHandler GetLoginsCompleted;
        
        /// <remarks/>
        public event DeleteLoginCompletedEventHandler DeleteLoginCompleted;
        
        /// <remarks/>
        public event GetTopicByIdCompletedEventHandler GetTopicByIdCompleted;
        
        /// <remarks/>
        public event CreateOrUpdateTopicCompletedEventHandler CreateOrUpdateTopicCompleted;
        
        /// <remarks/>
        public event GetTopicsCountCompletedEventHandler GetTopicsCountCompleted;
        
        /// <remarks/>
        public event GetTopicsCompletedEventHandler GetTopicsCompleted;
        
        /// <remarks/>
        public event DeleteTopicCompletedEventHandler DeleteTopicCompleted;
        
        /// <remarks/>
        public event GetBlogByIdCompletedEventHandler GetBlogByIdCompleted;
        
        /// <remarks/>
        public event GetBlogsCountCompletedEventHandler GetBlogsCountCompleted;
        
        /// <remarks/>
        public event GetBlogsCompletedEventHandler GetBlogsCompleted;
        
        /// <remarks/>
        public event GetVersionCompletedEventHandler GetVersionCompleted;
        
        /// <remarks/>
        public event GetTitleCompletedEventHandler GetTitleCompleted;
        
        /// <remarks/>
        public event GetCopyrightCompletedEventHandler GetCopyrightCompleted;
        
        /// <remarks/>
        public event GetDescriptionCompletedEventHandler GetDescriptionCompleted;
        
        /// <remarks/>
        public event GetUptimeCompletedEventHandler GetUptimeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dblock.org/ns/Login", RequestNamespace="http://dblock.org/ns/", ResponseNamespace="http://dblock.org/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Login(string username, string password) {
            object[] results = this.Invoke("Login", new object[] {
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string username, string password) {
            this.LoginAsync(username, password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string username, string password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        username,
                        password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dblock.org/ns/GetLogin", RequestNamespace="http://dblock.org/ns/", ResponseNamespace="http://dblock.org/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransitLogin GetLogin(string ticket) {
            object[] results = this.Invoke("GetLogin", new object[] {
                        ticket});
            return ((TransitLogin)(results[0]));
        }
        
        /// <remarks/>
        public void GetLoginAsync(string ticket) {
            this.GetLoginAsync(ticket, null);
        }
        
        /// <remarks/>
        public void GetLoginAsync(string ticket, object userState) {
            if ((this.GetLoginOperationCompleted == null)) {
                this.GetLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLoginOperationCompleted);
            }
            this.InvokeAsync("GetLogin", new object[] {
                        ticket}, this.GetLoginOperationCompleted, userState);
        }
        
        private void OnGetLoginOperationCompleted(object arg) {
            if ((this.GetLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLoginCompleted(this, new GetLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dblock.org/ns/GetLoginById", RequestNamespace="http://dblock.org/ns/", ResponseNamespace="http://dblock.org/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransitLogin GetLoginById(string ticket, int id) {
            object[] results = this.Invoke("GetLoginById", new object[] {
                        ticket,
                        id});
            return ((TransitLogin)(results[0]));
        }
        
        /// <remarks/>
        public void GetLoginByIdAsync(string ticket, int id) {
            this.GetLoginByIdAsync(ticket, id, null);
        }
        
        /// <remarks/>
        public void GetLoginByIdAsync(string ticket, int id, object userState) {
            if ((this.GetLoginByIdOperationCompleted == null)) {
                this.GetLoginByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLoginByIdOperationCompleted);
            }
            this.InvokeAsync("GetLoginById", new object[] {
                        ticket,
                        id}, this.GetLoginByIdOperationCompleted, userState);
        }
        
        private void OnGetLoginByIdOperationCompleted(object arg) {
            if ((this.GetLoginByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLoginByIdCompleted(this, new GetLoginByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dblock.org/ns/CreateOrUpdateLogin", RequestNamespace="http://dblock.org/ns/", ResponseNamespace="http://dblock.org/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateOrUpdateLogin(string ticket, TransitLogin t_login) {
            object[] results = this.Invoke("CreateOrUpdateLogin", new object[] {
                        ticket,
                        t_login});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateOrUpdateLoginAsync(string ticket, TransitLogin t_login) {
            this.CreateOrUpdateLoginAsync(ticket, t_login, null);
        }
        
        /// <remarks/>
        public void CreateOrUpdateLoginAsync(string ticket, TransitLogin t_login, object userState) {
            if ((this.CreateOrUpdateLoginOperationCompleted == null)) {
                this.CreateOrUpdateLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOrUpdateLoginOperationCompleted);
            }
            this.InvokeAsync("CreateOrUpdateLogin", new object[] {
                        ticket,
                        t_login}, this.CreateOrUpdateLoginOperationCompleted, userState);
        }
        
        private void OnCreateOrUpdateLoginOperationCompleted(object arg) {
            if ((this.CreateOrUpdateLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOrUpdateLoginCompleted(this, new CreateOrUpdateLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dblock.org/ns/GetLoginsCount", RequestNamespace="http://dblock.org/ns/", ResponseNamespace="http://dblock.org/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetLoginsCount(string ticket) {
            object[] results = this.Invoke("GetLoginsCount", new object[] {
                        ticket});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetLoginsCountAsync(string ticket) {
            this.GetLoginsCountAsync(ticket, null);
        }
        
        /// <remarks/>
        public void GetLoginsCountAsync(string ticket, object userState) {
            if ((this.GetLoginsCountOperationCompleted == null)) {
                this.GetLoginsCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLoginsCountOperationCompleted);
            }
            this.InvokeAsync("GetLoginsCount", new object[] {
                        ticket}, this.GetLoginsCountOperationCompleted, userState);
        }
        
        private void OnGetLoginsCountOperationCompleted(object arg) {
            if ((this.GetLoginsCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLoginsCountCompleted(this, new GetLoginsCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dblock.org/ns/GetLogins", RequestNamespace="http://dblock.org/ns/", ResponseNamespace="http://dblock.org/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransitLogin[] GetLogins(string ticket, WebServiceQueryOptions options) {
            object[] results = this.Invoke("GetLogins", new object[] {
                        ticket,
                        options});
            return ((TransitLogin[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLoginsAsync(string ticket, WebServiceQueryOptions options) {
            this.GetLoginsAsync(ticket, options, null);
        }
        
        /// <remarks/>
        public void GetLoginsAsync(string ticket, WebServiceQueryOptions options, object userState) {
            if ((this.GetLoginsOperationCompleted == null)) {
                this.GetLoginsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLoginsOperationCompleted);
            }
            this.InvokeAsync("GetLogins", new object[] {
                        ticket,
                        options}, this.GetLoginsOperationCompleted, userState);
        }
        
        private void OnGetLoginsOperationCompleted(object arg) {
            if ((this.GetLoginsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLoginsCompleted(this, new GetLoginsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dblock.org/ns/DeleteLogin", RequestNamespace="http://dblock.org/ns/", ResponseNamespace="http://dblock.org/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteLogin(string ticket, int id) {
            this.Invoke("DeleteLogin", new object[] {
                        ticket,
                        id});
        }
        
        /// <remarks/>
        public void DeleteLoginAsync(string ticket, int id) {
            this.DeleteLoginAsync(ticket, id, null);
        }
        
        /// <remarks/>
        public void DeleteLoginAsync(string ticket, int id, object userState) {
            if ((this.DeleteLoginOperationCompleted == null)) {
                this.DeleteLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteLoginOperationCompleted);
            }
            this.InvokeAsync("DeleteLogin", new object[] {
                        ticket,
                        id}, this.DeleteLoginOperationCompleted, userState);
        }
        
        private void OnDeleteLoginOperationCompleted(object arg) {
            if ((this.DeleteLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteLoginCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dblock.org/ns/GetTopicById", RequestNamespace="http://dblock.org/ns/", ResponseNamespace="http://dblock.org/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransitTopic GetTopicById(string ticket, int id) {
            object[] results = this.Invoke("GetTopicById", new object[] {
                        ticket,
                        id});
            return ((TransitTopic)(results[0]));
        }
        
        /// <remarks/>
        public void GetTopicByIdAsync(string ticket, int id) {
            this.GetTopicByIdAsync(ticket, id, null);
        }
        
        /// <remarks/>
        public void GetTopicByIdAsync(string ticket, int id, object userState) {
            if ((this.GetTopicByIdOperationCompleted == null)) {
                this.GetTopicByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTopicByIdOperationCompleted);
            }
            this.InvokeAsync("GetTopicById", new object[] {
                        ticket,
                        id}, this.GetTopicByIdOperationCompleted, userState);
        }
        
        private void OnGetTopicByIdOperationCompleted(object arg) {
            if ((this.GetTopicByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTopicByIdCompleted(this, new GetTopicByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dblock.org/ns/CreateOrUpdateTopic", RequestNamespace="http://dblock.org/ns/", ResponseNamespace="http://dblock.org/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateOrUpdateTopic(string ticket, TransitTopic t_topic) {
            object[] results = this.Invoke("CreateOrUpdateTopic", new object[] {
                        ticket,
                        t_topic});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateOrUpdateTopicAsync(string ticket, TransitTopic t_topic) {
            this.CreateOrUpdateTopicAsync(ticket, t_topic, null);
        }
        
        /// <remarks/>
        public void CreateOrUpdateTopicAsync(string ticket, TransitTopic t_topic, object userState) {
            if ((this.CreateOrUpdateTopicOperationCompleted == null)) {
                this.CreateOrUpdateTopicOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOrUpdateTopicOperationCompleted);
            }
            this.InvokeAsync("CreateOrUpdateTopic", new object[] {
                        ticket,
                        t_topic}, this.CreateOrUpdateTopicOperationCompleted, userState);
        }
        
        private void OnCreateOrUpdateTopicOperationCompleted(object arg) {
            if ((this.CreateOrUpdateTopicCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOrUpdateTopicCompleted(this, new CreateOrUpdateTopicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dblock.org/ns/GetTopicsCount", RequestNamespace="http://dblock.org/ns/", ResponseNamespace="http://dblock.org/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetTopicsCount(string ticket) {
            object[] results = this.Invoke("GetTopicsCount", new object[] {
                        ticket});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetTopicsCountAsync(string ticket) {
            this.GetTopicsCountAsync(ticket, null);
        }
        
        /// <remarks/>
        public void GetTopicsCountAsync(string ticket, object userState) {
            if ((this.GetTopicsCountOperationCompleted == null)) {
                this.GetTopicsCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTopicsCountOperationCompleted);
            }
            this.InvokeAsync("GetTopicsCount", new object[] {
                        ticket}, this.GetTopicsCountOperationCompleted, userState);
        }
        
        private void OnGetTopicsCountOperationCompleted(object arg) {
            if ((this.GetTopicsCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTopicsCountCompleted(this, new GetTopicsCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dblock.org/ns/GetTopics", RequestNamespace="http://dblock.org/ns/", ResponseNamespace="http://dblock.org/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransitTopic[] GetTopics(string ticket, WebServiceQueryOptions options) {
            object[] results = this.Invoke("GetTopics", new object[] {
                        ticket,
                        options});
            return ((TransitTopic[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTopicsAsync(string ticket, WebServiceQueryOptions options) {
            this.GetTopicsAsync(ticket, options, null);
        }
        
        /// <remarks/>
        public void GetTopicsAsync(string ticket, WebServiceQueryOptions options, object userState) {
            if ((this.GetTopicsOperationCompleted == null)) {
                this.GetTopicsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTopicsOperationCompleted);
            }
            this.InvokeAsync("GetTopics", new object[] {
                        ticket,
                        options}, this.GetTopicsOperationCompleted, userState);
        }
        
        private void OnGetTopicsOperationCompleted(object arg) {
            if ((this.GetTopicsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTopicsCompleted(this, new GetTopicsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dblock.org/ns/DeleteTopic", RequestNamespace="http://dblock.org/ns/", ResponseNamespace="http://dblock.org/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteTopic(string ticket, int id) {
            this.Invoke("DeleteTopic", new object[] {
                        ticket,
                        id});
        }
        
        /// <remarks/>
        public void DeleteTopicAsync(string ticket, int id) {
            this.DeleteTopicAsync(ticket, id, null);
        }
        
        /// <remarks/>
        public void DeleteTopicAsync(string ticket, int id, object userState) {
            if ((this.DeleteTopicOperationCompleted == null)) {
                this.DeleteTopicOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteTopicOperationCompleted);
            }
            this.InvokeAsync("DeleteTopic", new object[] {
                        ticket,
                        id}, this.DeleteTopicOperationCompleted, userState);
        }
        
        private void OnDeleteTopicOperationCompleted(object arg) {
            if ((this.DeleteTopicCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteTopicCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dblock.org/ns/GetBlogById", RequestNamespace="http://dblock.org/ns/", ResponseNamespace="http://dblock.org/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransitBlog GetBlogById(string ticket, int id) {
            object[] results = this.Invoke("GetBlogById", new object[] {
                        ticket,
                        id});
            return ((TransitBlog)(results[0]));
        }
        
        /// <remarks/>
        public void GetBlogByIdAsync(string ticket, int id) {
            this.GetBlogByIdAsync(ticket, id, null);
        }
        
        /// <remarks/>
        public void GetBlogByIdAsync(string ticket, int id, object userState) {
            if ((this.GetBlogByIdOperationCompleted == null)) {
                this.GetBlogByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBlogByIdOperationCompleted);
            }
            this.InvokeAsync("GetBlogById", new object[] {
                        ticket,
                        id}, this.GetBlogByIdOperationCompleted, userState);
        }
        
        private void OnGetBlogByIdOperationCompleted(object arg) {
            if ((this.GetBlogByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBlogByIdCompleted(this, new GetBlogByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dblock.org/ns/GetBlogsCount", RequestNamespace="http://dblock.org/ns/", ResponseNamespace="http://dblock.org/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetBlogsCount(string ticket, TransitBlogQueryOptions options) {
            object[] results = this.Invoke("GetBlogsCount", new object[] {
                        ticket,
                        options});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetBlogsCountAsync(string ticket, TransitBlogQueryOptions options) {
            this.GetBlogsCountAsync(ticket, options, null);
        }
        
        /// <remarks/>
        public void GetBlogsCountAsync(string ticket, TransitBlogQueryOptions options, object userState) {
            if ((this.GetBlogsCountOperationCompleted == null)) {
                this.GetBlogsCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBlogsCountOperationCompleted);
            }
            this.InvokeAsync("GetBlogsCount", new object[] {
                        ticket,
                        options}, this.GetBlogsCountOperationCompleted, userState);
        }
        
        private void OnGetBlogsCountOperationCompleted(object arg) {
            if ((this.GetBlogsCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBlogsCountCompleted(this, new GetBlogsCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dblock.org/ns/GetBlogs", RequestNamespace="http://dblock.org/ns/", ResponseNamespace="http://dblock.org/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransitBlog[] GetBlogs(string ticket, TransitBlogQueryOptions options) {
            object[] results = this.Invoke("GetBlogs", new object[] {
                        ticket,
                        options});
            return ((TransitBlog[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBlogsAsync(string ticket, TransitBlogQueryOptions options) {
            this.GetBlogsAsync(ticket, options, null);
        }
        
        /// <remarks/>
        public void GetBlogsAsync(string ticket, TransitBlogQueryOptions options, object userState) {
            if ((this.GetBlogsOperationCompleted == null)) {
                this.GetBlogsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBlogsOperationCompleted);
            }
            this.InvokeAsync("GetBlogs", new object[] {
                        ticket,
                        options}, this.GetBlogsOperationCompleted, userState);
        }
        
        private void OnGetBlogsOperationCompleted(object arg) {
            if ((this.GetBlogsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBlogsCompleted(this, new GetBlogsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dblock.org/ns/GetVersion", RequestNamespace="http://dblock.org/ns/", ResponseNamespace="http://dblock.org/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetVersion() {
            object[] results = this.Invoke("GetVersion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetVersionAsync() {
            this.GetVersionAsync(null);
        }
        
        /// <remarks/>
        public void GetVersionAsync(object userState) {
            if ((this.GetVersionOperationCompleted == null)) {
                this.GetVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVersionOperationCompleted);
            }
            this.InvokeAsync("GetVersion", new object[0], this.GetVersionOperationCompleted, userState);
        }
        
        private void OnGetVersionOperationCompleted(object arg) {
            if ((this.GetVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVersionCompleted(this, new GetVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dblock.org/ns/GetTitle", RequestNamespace="http://dblock.org/ns/", ResponseNamespace="http://dblock.org/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTitle() {
            object[] results = this.Invoke("GetTitle", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTitleAsync() {
            this.GetTitleAsync(null);
        }
        
        /// <remarks/>
        public void GetTitleAsync(object userState) {
            if ((this.GetTitleOperationCompleted == null)) {
                this.GetTitleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTitleOperationCompleted);
            }
            this.InvokeAsync("GetTitle", new object[0], this.GetTitleOperationCompleted, userState);
        }
        
        private void OnGetTitleOperationCompleted(object arg) {
            if ((this.GetTitleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTitleCompleted(this, new GetTitleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dblock.org/ns/GetCopyright", RequestNamespace="http://dblock.org/ns/", ResponseNamespace="http://dblock.org/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCopyright() {
            object[] results = this.Invoke("GetCopyright", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCopyrightAsync() {
            this.GetCopyrightAsync(null);
        }
        
        /// <remarks/>
        public void GetCopyrightAsync(object userState) {
            if ((this.GetCopyrightOperationCompleted == null)) {
                this.GetCopyrightOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCopyrightOperationCompleted);
            }
            this.InvokeAsync("GetCopyright", new object[0], this.GetCopyrightOperationCompleted, userState);
        }
        
        private void OnGetCopyrightOperationCompleted(object arg) {
            if ((this.GetCopyrightCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCopyrightCompleted(this, new GetCopyrightCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dblock.org/ns/GetDescription", RequestNamespace="http://dblock.org/ns/", ResponseNamespace="http://dblock.org/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDescription() {
            object[] results = this.Invoke("GetDescription", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDescriptionAsync() {
            this.GetDescriptionAsync(null);
        }
        
        /// <remarks/>
        public void GetDescriptionAsync(object userState) {
            if ((this.GetDescriptionOperationCompleted == null)) {
                this.GetDescriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDescriptionOperationCompleted);
            }
            this.InvokeAsync("GetDescription", new object[0], this.GetDescriptionOperationCompleted, userState);
        }
        
        private void OnGetDescriptionOperationCompleted(object arg) {
            if ((this.GetDescriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDescriptionCompleted(this, new GetDescriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dblock.org/ns/GetUptime", RequestNamespace="http://dblock.org/ns/", ResponseNamespace="http://dblock.org/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long GetUptime() {
            object[] results = this.Invoke("GetUptime", new object[0]);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void GetUptimeAsync() {
            this.GetUptimeAsync(null);
        }
        
        /// <remarks/>
        public void GetUptimeAsync(object userState) {
            if ((this.GetUptimeOperationCompleted == null)) {
                this.GetUptimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUptimeOperationCompleted);
            }
            this.InvokeAsync("GetUptime", new object[0], this.GetUptimeOperationCompleted, userState);
        }
        
        private void OnGetUptimeOperationCompleted(object arg) {
            if ((this.GetUptimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUptimeCompleted(this, new GetUptimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dblock.org/ns/")]
    public partial class TransitLogin : TransitObject {
        
        private string nameField;
        
        private string emailField;
        
        private TransitLoginRole roleField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string websiteField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public TransitLoginRole Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Website {
            get {
                return this.websiteField;
            }
            set {
                this.websiteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dblock.org/ns/")]
    public enum TransitLoginRole {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Guest,
        
        /// <remarks/>
        Administrator,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransitBlog))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransitTopic))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransitLogin))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dblock.org/ns/")]
    public partial class TransitObject {
        
        private int idField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransitBlogQueryOptions))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dblock.org/ns/")]
    public partial class WebServiceQueryOptions {
        
        private int pageSizeField;
        
        private int pageNumberField;
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        public int PageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dblock.org/ns/")]
    public partial class TransitBlogQueryOptions : WebServiceQueryOptions {
        
        private int topicIdField;
        
        /// <remarks/>
        public int TopicId {
            get {
                return this.topicIdField;
            }
            set {
                this.topicIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dblock.org/ns/")]
    public partial class TransitBlog : TransitObject {
        
        private string titleField;
        
        private string typeField;
        
        private System.DateTime createdField;
        
        private System.DateTime modifiedField;
        
        private string textField;
        
        private string topicNameField;
        
        private int topicIdField;
        
        private int templateIdField;
        
        private int ownerLoginIdField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
            }
        }
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public string TopicName {
            get {
                return this.topicNameField;
            }
            set {
                this.topicNameField = value;
            }
        }
        
        /// <remarks/>
        public int TopicId {
            get {
                return this.topicIdField;
            }
            set {
                this.topicIdField = value;
            }
        }
        
        /// <remarks/>
        public int TemplateId {
            get {
                return this.templateIdField;
            }
            set {
                this.templateIdField = value;
            }
        }
        
        /// <remarks/>
        public int OwnerLoginId {
            get {
                return this.ownerLoginIdField;
            }
            set {
                this.ownerLoginIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dblock.org/ns/")]
    public partial class TransitTopic : TransitObject {
        
        private string nameField;
        
        private string typeField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetLoginCompletedEventHandler(object sender, GetLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransitLogin Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransitLogin)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetLoginByIdCompletedEventHandler(object sender, GetLoginByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLoginByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLoginByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransitLogin Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransitLogin)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void CreateOrUpdateLoginCompletedEventHandler(object sender, CreateOrUpdateLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateOrUpdateLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateOrUpdateLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetLoginsCountCompletedEventHandler(object sender, GetLoginsCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLoginsCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLoginsCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetLoginsCompletedEventHandler(object sender, GetLoginsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLoginsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLoginsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransitLogin[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransitLogin[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void DeleteLoginCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetTopicByIdCompletedEventHandler(object sender, GetTopicByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTopicByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTopicByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransitTopic Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransitTopic)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void CreateOrUpdateTopicCompletedEventHandler(object sender, CreateOrUpdateTopicCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateOrUpdateTopicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateOrUpdateTopicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetTopicsCountCompletedEventHandler(object sender, GetTopicsCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTopicsCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTopicsCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetTopicsCompletedEventHandler(object sender, GetTopicsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTopicsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTopicsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransitTopic[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransitTopic[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void DeleteTopicCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetBlogByIdCompletedEventHandler(object sender, GetBlogByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBlogByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBlogByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransitBlog Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransitBlog)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetBlogsCountCompletedEventHandler(object sender, GetBlogsCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBlogsCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBlogsCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetBlogsCompletedEventHandler(object sender, GetBlogsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBlogsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBlogsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransitBlog[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransitBlog[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetVersionCompletedEventHandler(object sender, GetVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetTitleCompletedEventHandler(object sender, GetTitleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTitleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTitleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetCopyrightCompletedEventHandler(object sender, GetCopyrightCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCopyrightCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCopyrightCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetDescriptionCompletedEventHandler(object sender, GetDescriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDescriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDescriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetUptimeCompletedEventHandler(object sender, GetUptimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUptimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUptimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591